application: gps-maps27
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"

inbound_services:
- channel_presence

admin_console:
  pages:
  - name: Appstats
    url: /stats

handlers:
#- url: /_ah/queue/deferred
#  script: libs.deferred.app
#  #script: google.appengine.ext.deferred.application
#  #login: admin

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app

#- url: /prodeagle/
#  script: prodeagle.harvest.application

- url: /prodeagle/.*
  static_files: static/blanks.html
  upload: static/blanks.html

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /html
  static_dir: html

- url: /svg
  static_dir: svg
  mime_type: image/svg+xml

- url: /images/(.*\.(gif|png|jpg|ico))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg|ico))

#- url: /_ah/channel/.*
#  script: channel.app

- url: /.*
  script: application.app
